name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '*/10 * * * *'  # Alle 10 Minuten
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python-Version festlegen
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache für Poetry installieren
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            **/site-packages
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Poetry installieren
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Abhängigkeiten installieren
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run pip install --no-cache-dir charset-normalizer==3.3.0  # Fix für charset-normalizer
          poetry install --no-interaction --no-ansi

      - name: Linting mit flake8
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run flake8 .

      - name: Tests ausführen
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run pytest

  collect-data:
    needs: build-and-test
    if: github.repository_owner == 'raphaelkach'
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python-Version festlegen
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache für Poetry installieren
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            **/site-packages
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Poetry installieren
        run: |
          curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.2 python3 -
          export PATH="$HOME/.local/bin:$PATH"
          poetry --version

      - name: Abhängigkeiten installieren
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run pip install --no-cache-dir charset-normalizer==3.3.0  # Fix für charset-normalizer
          poetry install --no-interaction --no-ansi

      - name: Skript ausführen
        env:
          DB_CLIENT_ID: ${{ secrets.DB_CLIENT_ID }}
          DB_API_KEY: ${{ secrets.DB_API_KEY }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry run python main.py

      - name: Änderungen committen und pushen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatisches Update der gesammelten Daten'
          file_pattern: |
            01_data/01_raw/API/*
            01_data/01_raw/API/logs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Verwende das eingebaute GitHub Token
